name: Publish Snapshot
on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') && !startsWith(github.ref, 'refs/tags/v') }}
      - name: Check Licenses and Generate QMJs
        run: ./gradlew checkLicenses generateQmj --stacktrace
      - name: Publish to Snapshot maven
        run: ./gradlew build publish --stacktrace
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}

      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts (Java ${{ matrix.java }})
          path: ./*/build/libs/
